DROP TABLE IF EXISTS categories;
CREATE TABLE categories (
    category_id         SMALLINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_name       VARCHAR(15)     NOT NULL,
    description         TEXT            NULL,
    picture             BYTEA           NULL,
    CONSTRAINT pk_categories PRIMARY KEY (category_id)
);

DROP INDEX IF EXISTS ix_categories__category_id;
CREATE UNIQUE INDEX ix_categories__category_id ON categories (category_id);
CLUSTER categories USING ix_categories__category_id;

DROP INDEX IF EXISTS ix_categories__category_name;
CREATE INDEX ix_categories__category_name ON categories (category_name);
CLUSTER categories USING ix_categories__category_name;
