DROP TABLE IF EXISTS products;
CREATE TABLE products (
    product_id              INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_name            VARCHAR(40)     NOT NULL,
    supplier_id             INT             NULL,
    category_id             SMALLINT        NULL,
    quantity_per_unit       VARCHAR(20)     NULL,
    unit_price              REAL            CONSTRAINT df_products__unit_price DEFAULT (0) NULL,
    units_in_stock          SMALLINT        CONSTRAINT df_products__units_in_stock DEFAULT (0) NULL,
    units_on_order          SMALLINT        CONSTRAINT df_products__units_on_order DEFAULT (0) NULL,
    reorder_level           SMALLINT        CONSTRAINT df_products__reorder_level DEFAULT (0) NULL,
    discontinued            BOOLEAN         CONSTRAINT df_products__discontinued DEFAULT (FALSE) NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id),
    CONSTRAINT ck_unit_price CHECK (unit_price >= 0),
    CONSTRAINT ck_reorder_level CHECK (reorder_level >= 0),
    CONSTRAINT ck_units_in_stock CHECK (units_in_stock >= 0),
    CONSTRAINT ck_units_on_order CHECK (units_on_order >= 0)
);

DROP INDEX IF EXISTS ix_products__product_id;
CREATE UNIQUE INDEX ix_products__product_id ON products (product_id);
CLUSTER products USING ix_products__product_id;

DROP INDEX IF EXISTS ix_products__category_id;
CREATE INDEX ix_products__category_id ON products (category_id);
CLUSTER products USING ix_products__category_id;

DROP INDEX IF EXISTS ix_products__product_name;
CREATE INDEX ix_products__product_name ON products (product_name);
CLUSTER products USING ix_products__product_name;

DROP INDEX IF EXISTS ix_products__supplier_id;
CREATE INDEX ix_products__supplier_id ON products (supplier_id);
CLUSTER products USING ix_products__supplier_id;
